services:

  mysql:
    image: mysql:8.0
    container_name: demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: MySQL@123#!
      MYSQL_DATABASE: project_01_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pMySQL@123#!"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - demo-network

  app:
    build: .
    container_name: demo-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://demo-mysql:3306/project_01_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MySQL@123#!
      JWT_SECRET: 75JIDVqGDgdEdBI01f3QjszjMt4dNevp6N6dvIp57kWsglc9bzEWNZxDZS4ldk7exBHprY3OAKzX7HVROefnq0
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

volumes:
  mysql-data: